#!/usr/bin/env python3
"""Trim the 2026-10-08 article bodies in the generator to ~480-550 words."""
import pathlib

p = pathlib.Path.home() / "projects/grc-portfolio/scripts/_gen_articles_2026-10-08.py"
src = p.read_text()

repl = [
("Cracked credentials were sorted and prioritized by organization revenue and network structure, and new administrative accounts were created on the firewall to keep access.",
 "New administrative accounts are created on the appliance to keep access."),
("That is a policy, monitoring and training problem, and it shows up in almost every environment that has never audited whether administrative passwords on network devices are unique.",
 "That is a policy and monitoring problem, and it shows up in most environments that have never audited whether device administrative passwords are unique."),
("Moving administrator credentials to PBKDF2 is not a research project, it is a documented action item, and it is one of the easiest ways to reduce the value of a stolen hash.",
 "Moving administrator credentials to PBKDF2 is a documented action item, not a research project, and it reduces the value of a stolen hash."),
("Break-glass access, offline configuration backups and a documented way to rebuild the appliance belong in the runbook before an incident, not during one.",
 "Break-glass access, offline configuration backups and a documented rebuild path belong in the runbook before an incident, not during one."),
("Either move would attach a remediation deadline for federal agencies and give private sector security teams a deadline they can take to their own leadership. Watch also for the first ransomware deployment publicly attributed to access sold out of this campaign. Cost and urgency tend to become real at that point for boards that have ignored the advisory so far.",
 "Either move attaches an agency remediation deadline and gives private sector teams a date they can take to their own leadership. Watch also for the first ransomware deployment publicly attributed to access sold out of this campaign, because that is when board-level attention usually arrives."),
("The practical work is unglamorous. Inventory every appliance reachable from the internet, confirm administrative credentials are unique and stored with PBKDF2, disable SSL VPN portals nobody uses, require phishing-resistant multi-factor authentication for administrative access, and keep an out-of-band way to regain control of a device if an account disappears.",
 "The practical work is unglamorous. Inventory every appliance reachable from the internet, confirm administrative credentials are unique and stored with PBKDF2, require phishing-resistant multi-factor authentication, and keep an out-of-band way to regain control of a device if an account disappears."),
("The intent is to replace a patchwork of agency specific terminology, such as \"sensitive but unclassified\" and \"for official use only,\" with a single standard. As one attorney advising contractors put it, the goal is to make it easier to comply with one set of standards rather than many. The article notes that the effort traces back to a 2010 executive order. A practical complication remains: CUI is not always clearly marked, and contractors often cannot say with confidence which of the information they hold actually falls into the category.",
 "The intent is to replace a patchwork of agency specific terms such as \"sensitive but unclassified\" and \"for official use only\" with a single standard, so contractors comply with one set of rules rather than many. The effort traces back to a 2010 executive order. One practical complication remains: CUI is not always clearly marked, and contractors often cannot say with confidence which information they hold falls into the category."),
("A contractor that cannot show when an incident was identified, and what was known at that moment, will struggle to demonstrate it reported on time. Log retention and incident documentation stop being IT housekeeping and become the record of compliance.",
 "A contractor that cannot show when an incident was identified, and what was known at the time, will struggle to demonstrate it reported on time. Log retention and incident documentation stop being housekeeping."),
("Consolidating many agency requirements into NIST SP 800-171 should reduce duplicated effort. The same attorneys point out that broader applicability also means mid-sized and smaller contractors inherit requirements they may not have staffed for. Data classification becomes the gating control. If you cannot reliably identify CUI in your environment, you cannot protect it or report on it.",
 "Consolidating many agency requirements into NIST SP 800-171 should reduce duplicated effort, while broader applicability means smaller contractors inherit requirements they may not have staffed for. Data classification becomes the gating control. If you cannot reliably identify CUI in your environment, you cannot protect or report on it."),
("Prime contractors pass these obligations to subcontractors. A supplier that has never run a NIST based control assessment may soon find it is a contract condition, which is why the practical question for many companies is not whether they comply but whether they can evidence it quickly when asked.",
 "Prime contractors pass these obligations to subcontractors. A supplier that has never run a NIST based assessment may soon find it is a contract condition."),
("Watch also whether the reporting channel is unified with existing cyber incident reporting requirements, because overlapping deadlines for the same event are a compliance trap that has bitten regulated industries before.",
 "Watch also whether the reporting channel is unified with existing cyber incident reporting requirements, because overlapping deadlines for the same event are a compliance trap."),
("If your organization holds government data, the work to start now is a plain inventory: which contracts involve CUI, who owns the control set, where the evidence lives, and how quickly you could produce a defensible timeline of discovery if an incident happened this week.",
 "If your organization holds government data, start with a plain inventory: which contracts involve CUI, who owns the control set, where the evidence lives, and how quickly you could produce a defensible timeline of discovery if an incident happened this week."),
("He faces one count of conspiracy to commit wire fraud and two counts of wire fraud over an alleged scheme that prosecutors say ran from June 2018 to June 2023. The US Attorney's Office told BleepingComputer that Pinhasi surrendered, pleaded not guilty and was released on a $2 million bond.",
 "He faces one count of conspiracy to commit wire fraud and two counts of wire fraud. Prosecutors say the alleged scheme ran from June 2018 to June 2023. The US Attorney's Office told BleepingComputer that Pinhasi surrendered, pleaded not guilty and was released on a $2 million bond."),
("According to the indictment, Pinhasi owned and operated MonsterCloud LLC, a Florida based company that advertised tools and decryption techniques for recovering encrypted data without paying cybercriminals. Prosecutors allege the company had no such technology and instead contacted ransomware operators, paid for decryption keys, and used those keys to restore customer files. Some contracts did disclose that the company might communicate with or pay cybercriminals, but the indictment says those contracts stated it would do so only if files could not be decrypted by other means, while dealing with attackers was usually the first step taken.",
 "According to the indictment, Pinhasi owned and operated MonsterCloud LLC, a Florida based company that advertised tools for recovering encrypted data without paying cybercriminals. Prosecutors allege it had no such technology and instead contacted ransomware operators, paid for keys, and used those keys to restore customer files. Some contracts disclosed that the company might pay cybercriminals, the indictment says, but those contracts stated it would do so only if files could not be decrypted by other means, while dealing with attackers was usually the first step taken."),
("The charging documents allege that customers were charged far more than the ransoms paid, citing one recovery where about $8,200 was paid to a gang and roughly $150,000 was charged to the victim, and another where about $236,000 was paid and about $380,000 was charged. Prosecutors also say decrypted sample files were presented as \"recovery proofs\" to convince victims the company could restore their data. In total, the indictment alleges the scheme facilitated more than $8 million in ransom payments while charging hundreds of companies in the United States and Canada more than $19 million for recovery and remediation. If convicted, Pinhasi faces up to 20 years in prison. A 2019 ProPublica investigation raised similar concerns, which Pinhasi disputed at the time.",
 "Customers were allegedly charged far more than the ransoms paid. One recovery cited in the indictment involved about $8,200 paid to a gang and roughly $150,000 charged to the victim; another involved about $236,000 paid and about $380,000 charged. Prosecutors also say decrypted sample files were presented as \"recovery proofs.\" In total, the scheme is alleged to have facilitated more than $8 million in ransom payments while charging hundreds of companies in the United States and Canada more than $19 million. If convicted, Pinhasi faces up to 20 years in prison. A 2019 ProPublica investigation raised similar concerns, which he disputed at the time."),
("Incident response is bought in a hurry, usually under pressure, often without the diligence applied to any other critical supplier. When a provider's core selling point is a capability nobody can verify, the buyer is relying on marketing. Contract terms that describe a method, a decision point, and who authorizes a payment are more useful than a promise of recovery.",
 "Incident response is bought in a hurry, often without the diligence applied to any other critical supplier. When a provider's core selling point is a capability nobody can verify, the buyer is relying on marketing. Contract terms that describe a method, a decision point and who authorizes a payment are more useful than a promise of recovery."),
("The allegation here is that payments happened without the victim knowing, which removes the victim's ability to make that call at all.",
 "The allegation here is that payments happened without the victim knowing."),
("A recovery engagement should produce a timeline, a description of the method used, and a clear record of what was paid, to whom and on whose authority. Those records are what auditors, regulators and insurers ask for, and they are also what separates a legitimate provider from one that cannot explain its work.",
 "A recovery engagement should produce a timeline, a description of the method used, and a record of what was paid, to whom and on whose authority."),
("Watch whether the case prompts clearer disclosure expectations for incident response providers, since this is a fraud matter rather than a security failure and the allegations are specific enough to be uncomfortable for the whole recovery market. Watch also for how insurers respond. Insurers routinely require pre-approval before a payment is made, and a case built on payments happening without the client's knowledge gives them a reason to tighten verification requirements further.",
 "Watch whether the case prompts clearer disclosure expectations for incident response providers, since this is a fraud matter rather than a security failure. Watch also for how insurers respond, because a case built on secret payments gives them a reason to tighten verification of pre-approval."),
("The practical takeaway for a security or risk leader is short. Know who you would call during a ransomware event before you need to, ask how they recover data and whether any payment is involved, and put the authorization path in writing while everyone is calm.",
 "The practical takeaway is short. Know who you would call during a ransomware event before you need to, ask how they recover data and whether any payment is involved, and put the authorization path in writing."),
("The coalition points to scale. Agencies rely on OT in more than 8,000 General Services Administration managed facilities, including laboratories, hospitals and ports of entry, where the technology runs HVAC, power, access control, water and building automation systems. The request follows a Government Accountability Office report published on September 30, which found that only seven of 22 civilian agencies reviewed had fully met Office of Management and Budget requirements to inventory their networked OT and Internet of Things devices. Those inventories were due by September 2024, and the GAO said OMB had not issued updated guidance for fiscal year 2026.",
 "The coalition points to scale. Agencies rely on OT in more than 8,000 General Services Administration managed facilities, including laboratories, hospitals and ports of entry, where the technology runs HVAC, power, access control, water and building automation systems. The request follows a Government Accountability Office report published on September 30, which found that only seven of 22 civilian agencies reviewed had fully met Office of Management and Budget requirements to inventory networked OT and Internet of Things devices. Those inventories were due by September 2024, and the GAO said OMB had not issued updated fiscal year 2026 guidance."),
("The coalition's priority controls include changing default passwords, multi-factor authentication, segmentation and backups, but the report does not call for patching or firmware updates, a gap that one industry vice president, John Gallagher of Viakoo, flagged publicly by noting that remediation is missing and that patch and configuration backlogs overwhelm operational teams. Louis Eichenbaum, federal chief technology officer at ColorTokens, argued that containment matters alongside prevention and said flatly that \"we cannot patch our way out of cyber risk.\" The coalition also framed the directive as complementary to CISA's CI Fortify resilience initiative.",
 "The coalition's priority controls include changing default passwords, multi-factor authentication, segmentation and backups, but the report does not call for patching or firmware updates. John Gallagher of Viakoo flagged that gap, noting that remediation is missing. Louis Eichenbaum, federal chief technology officer at ColorTokens, said containment matters alongside prevention and that \"we cannot patch our way out of cyber risk.\" The coalition framed the directive as complementary to CISA's CI Fortify resilience initiative."),
("The GAO finding is the important part of this story. A year past the deadline, most reviewed agencies still cannot fully account for their networked OT and IoT devices. You cannot risk assess, segment or recover what you have not counted, and the same is true in private sector environments where OT inventory is often owned by facilities rather than security.",
 "The GAO finding is the important part of this story. A year past the deadline, most reviewed agencies still cannot fully account for their networked OT and IoT devices. You cannot assess, segment or recover what you have not counted, and the same holds where OT inventory sits with facilities rather than security."),
("That is governance language, and it exists because responsibility for building systems and industrial control sits in different parts of an organization from cyber risk. A named owner with a seat in enterprise risk discussions is how those two worlds start communicating before an incident forces them to.",
 "That is governance language, and it exists because industrial control systems and cyber risk usually sit in different parts of an organization. A named owner with a seat in risk discussions is how those two worlds start talking before an incident forces them to."),
("The debate over whether to require patching reflects a real constraint: many industrial devices cannot be patched quickly without disrupting operations. Segmentation, offline recovery and tested restoration are the controls that buy time when patching is slow. Treating those as substitutes for patching is a risk decision that should be documented, not a default.",
 "Many industrial devices cannot be patched quickly without disrupting operations. Segmentation, offline recovery and tested restoration buy time when patching is slow. Treating them as substitutes for patching is a risk decision that should be documented."),
("Watch whether CISA acts on the request and, if it does, whether patching and firmware updates make it into the final text. Watch also for the OMB guidance that the GAO said was missing for fiscal year 2026. Guidance would tell agencies what a complete inventory looks like, which is the first measurable step.",
 "Watch whether CISA acts on the request and, if it does, whether patching and firmware updates make it into the final text. Watch also for the OMB guidance the GAO said was missing for fiscal year 2026, which would tell agencies what a complete inventory looks like."),
("For anyone running OT outside government, the direction of travel is useful even though binding directives do not apply to privately operated critical infrastructure. Federal baselines tend to become procurement expectations and then vendor requirements. The practical move now is the same one the coalition is asking agencies to make: know what is on the network, name an owner, and prove you can recover a segment without patching your way out of the problem.",
 "For anyone running OT outside government, the direction of travel still matters, even though binding directives do not apply to privately operated critical infrastructure. Federal baselines tend to become procurement expectations. Know what is on the network, name an owner, and prove you can recover a segment without patching your way out of the problem."),
("In its advisory, Google said that during the hijacks, attackers modified authoritative DNS records and obtained unauthorized HTTPS certificates covering several Google domains and domains belonging to other organizations. The company did not say which domains or organizations were affected. It said the attacks did not compromise Google systems, that Chrome quickly blocked suspected counterfeit certificates across the affected country code top level domains, and that there is no reason to believe the certification authorities that issued the impacted certificates did anything wrong.",
 "Google said that during the hijacks, attackers modified authoritative DNS records and obtained unauthorized HTTPS certificates covering several Google domains and domains belonging to other organizations. It did not say which domains or organizations were affected. The company said the attacks did not compromise Google systems, that Chrome quickly blocked suspected counterfeit certificates across the affected country code top level domains, and that there is no reason to believe the certification authorities that issued the impacted certificates did anything wrong."),
("Google was direct about the limits of its own intervention. The advisory said browser side action should not be relied on to protect users, that due to the complexity of DNS hijacks the company cannot guarantee its analysis identified every affected domain, and that Chrome's interventions do not reliably protect people using other browsers. Its recommendations for domain owners are ongoing monitoring of Certificate Transparency logs across all domains, including parked and regional country code properties, a review of recent CT log entries for any organization operating in .gh, .sl or .as, and the publication of restrictive Certification Authority Authorization records that name which authorities may issue certificates and which validation methods are permitted.",
 "Google was direct about the limits of its own intervention. It said browser side action should not be relied on to protect users, that due to the complexity of DNS hijacks it cannot guarantee its analysis identified every affected domain, and that Chrome's interventions do not reliably protect people using other browsers. Its recommendations are ongoing monitoring of Certificate Transparency logs across all domains, including parked and regional country code properties, a review of recent CT log entries for organizations operating in .gh, .sl or .as, and restrictive Certification Authority Authorization records naming which authorities may issue certificates."),
("Many organizations have domains they registered years ago for regional marketing, a redirect or brand protection, and nobody currently owns them. Those are exactly the properties Google points at. An asset register that covers servers and applications but not DNS zones and certificates has a blind spot that shows up at the trust layer, where users cannot tell the difference between the real site and a copy.",
 "Many organizations have domains registered years ago for a redirect or brand protection, and nobody currently owns them. Those are exactly the properties Google points at. An asset register that covers servers but not DNS zones and certificates has a blind spot at the trust layer, where users cannot tell the real site from a copy."),
("Monitoring CT logs gives near real time notice when a certificate is issued for a domain you control. It is one of the few detective controls that costs almost nothing to implement and produces high value alerts. Treating it as optional removes a control that would have surfaced this activity quickly.",
 "Monitoring CT logs gives near real time notice when a certificate is issued for a domain you control. It is one of the few detective controls that costs almost nothing and produces high value alerts."),
("Google explicitly did not blame the certification authorities. The lesson is structural: certificate issuance validation can be undermined by whoever controls the DNS answers at that moment. Registrars, DNS providers and certificate authorities are all part of the supply chain, and each deserves a named owner and a periodic review rather than a set and forget configuration.",
 "Google did not blame the certification authorities. The lesson is structural: certificate issuance validation can be undermined by whoever controls the DNS answers at that moment. Registrars, DNS providers and certificate authorities each deserve a named owner."),
("Watch whether the affected country code registries and registrars publish details on how authoritative records were changed, because the answer determines whether this was a registry compromise, an account takeover at a registrar, or a weakness in a delegation process. Watch also for whether the industry revisits how validation state is cached, since Google's guidance warns specifically about certificates being minted after a hijack ends using cached validation state.",
 "Watch whether the affected registries and registrars publish details on how authoritative records were changed, because that determines whether this was a registry compromise, an account takeover at a registrar, or a weakness in delegation. Watch also for whether the industry revisits cached validation state, which Google warns can be used to mint certificates after a hijack ends."),
("The practical actions are small and repeatable. List every domain you own, including the ones nobody uses, confirm which DNS provider holds each zone, turn on Certificate Transparency monitoring, publish CAA records that restrict which authorities may issue, and make sure registrar accounts have strong authentication and more than one person who can access them.",
 "The practical actions are small and repeatable. List every domain you own, including the ones nobody uses, confirm which DNS provider holds each zone, turn on Certificate Transparency monitoring, publish CAA records that restrict issuance, and protect registrar accounts with strong authentication."),
]

missed = []
for old, new in repl:
    if old in src:
        src = src.replace(old, new, 1)
    else:
        missed.append(old[:70])
p.write_text(src)
print("applied:", len(repl) - len(missed), "of", len(repl))
for m in missed:
    print(" MISS:", m)
